### ISSUE TITLE
Nav Bar || Search Bar

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/react-components#11]
This component requires the search-suggestion-panel component as a dependency.

Component tree

- search-bar
  - input(.search-bar__text)
  - img(.search-bar__icon)
  - search-suggestion-panel(.search-bar__dropdown)

Requirements:
- Create a branch off of master and make a PR to master
- Should be responsive as rendered in the design specks
- Should implement typeahead/autocomplete feature. For now, it can consume some JSON residing in the component itself, which will be made dynamic at the time of integration.

**Comment by reynard2007** [comment]
Taking this.

**Comment by vikasrohit** [comment]
@reynard2007 You can pick this up, however, this component would require search-suggestion-panel to be built first. So, may be you can pick first that or any component that depends on. Once you are done with them, you can pick this one as soon as you are done with that.

**Comment by reynard2007** [comment]
Thanks, @vikasrohit. I didn't realize that. Are you referring to Issue #7?

**Comment by vikasrohit** [comment]
@reynard2007  Sorry for any confusion. However, basically one has to pick first all those components which does not depend on any other component e.g. panel, dropdown, std list item etc. Once they are done (PR is generated and merged), anyone can start on components that are using them. We would try to be as fast as possible to review and merge the PRs. Even though if we have some minor issues/things to be fixed in that PR, we can close it for the sake of unblocking other components and ask you to fix those missing pieces in the same PR.

**Comment by reynard2007** [comment]
Got it. I'll take #4 then since it appears to be a generic component.

**Comment by reynard2007** [comment]
Taking this again.

**Comment by vikasrohit** [comment]
@reynard2007 it seems the watermark text, when user types something in the text box, is not aligned with what user is typing. Can you please take care of it?
<img width="76" alt="searchbar-text-watermark-aligment" src="https://cloud.githubusercontent.com/assets/2417632/13769901/2df7fa78-eaa9-11e5-9d79-934dc8f9f62a.png">

**Comment by reynard2007** [comment]
Made the fix already. I also changed the StandardListItem labelText propType to PropTypes.node to allow us to use a span DOM node for the emboldening effect on matching searches.

**Comment by vikasrohit** [comment]
Closing task. Thanks @reynard2007 for your hard work.
