### ISSUE TITLE
Nav Bar || Complete Nav Bar

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/react-components#12]
This component will be developed after all other components have been completed.

Component tree

- nav-bar
 - topcoder-logo
 - search-bar
 - menu-bar
 - quick-links-dropdown-menu
 - user-dropdown-menu

Requirements:
- Create a branch off of master and make a PR to master
- Should be responsive as rendered in the design specks

**Comment by reynard2007** [comment]
Taking this.

**Comment by vikasrohit** [comment]
Sorry for the delay, however just to confirm, you are good to go.

**Comment by reynard2007** [comment]
Thanks @vikasrohit. BTW, where can I find the login/join button components? Also, the scope of this task is only the top navigation bar and does not include the gray sub-navigation below?

**Comment by vikasrohit** [comment]
For now, you can have login/join button as simple buttons instead of being React components. And for sub-navigation is not the part of this task or challenge. We may have separate challenge for some other missing components like buttons and subnavigation etc.

**Comment by vikasrohit** [comment]
@reynard2007 As per specks, on mobile view (375px), we should be able to fit 6 elements (logo, 3 navigation links, 1 search icon, 1 icon for user details), however, as of now I think we are able to accommodate only 5 items, the last item is overflowing the device.

**Comment by reynard2007** [comment]
Hi @vikasrohit, acknowledging this and earlier comments. Will submit a new PR soon.

**Comment by vikasrohit** [comment]
Thanks @reynard2007

**Comment by reynard2007** [comment]
I am unable to replicate the overflow issue. This is what I am seeing on my browser:

![image](https://cloud.githubusercontent.com/assets/1097189/13783773/a3a5c42c-eb07-11e5-89c8-269c4dc83872.png)

**Comment by reynard2007** [comment]
Apologies. My browser was zoomed out to 60%. Will fix this.

**Comment by vikasrohit** [comment]
Closing task. Thanks @reynard2007 for your hard work.

**Comment by reynard2007** [comment]
My pleasure. Appreciate the advice you have given during this challenge :)
