### ISSUE TITLE
Progress Bar React component

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/react-components#51]
**Requirements**
- [x] Should be styled as shown in [specks](https://drive.google.com/drive/u/0/folders/0B1LbmKnex41fMkVfWFhSUlR3eGM) (Please see the timeline component)
- [x] Should support checkpoints
- [x] Without checkpoints there would be no checkpoint circles

**Comment by katat** [comment]
working on this.

**Comment by vikasrohit** [comment]
:+1: Go ahead

**Comment by vikasrohit** [comment]
@katat Please let us know here if you have any query.

**Comment by katat** [comment]
@vikasrohit I had a try and couldn't get enough time to finish it. Sorry. I remove the comment, so other can continue on this one.

**Comment by vikasrohit** [comment]
Thanks @katat for the update. I guess we still have enough time to get it done, if you feel comfortable working on this, please let us know.

**Comment by vikasrohit** [comment]
Task is available to be taken.

**Comment by amolskh** [comment]
I am taking this up
1) This refers to section timeline right?
2) Those circles and lines of progress will be drawn using css right?
3) can you provide some sample input about checkpoint data this component would use?

**Comment by vikasrohit** [comment]
1. yes
2. yes
3. Checkpoints are those circles that you are mentioning in the 2. And in simple words, they are just marked label in  the progress bar e.g. if we assume a progress bar to denote duration of 6 days from today and we have a checkpoint after 2 days, then there would be a circle in the progress bar at 2/6 of the full length.

**Comment by amolskh** [comment]
PR Done... Please review

**Comment by vikasrohit** [comment]
@amolskh 
Final fixes:

- [ ] Can you please include one more example with only two checkpoints?
- [ ] Can we also have examples with two checkpoints but not showing labels of either of them something like this:
![56a03fa4-fb2e-11e5-9082-9e63adab2a0a](https://cloud.githubusercontent.com/assets/2417632/14308776/f1baeec2-fbf5-11e5-8d05-f0c75e3bd762.png)
