### ISSUE TITLE
Prize and PrizeList React components

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/react-components#52]
Requirements
- [x] Two components PrizeItem and PrizeList where PrizeList may contain multiple PrizeItem(s)
- [x] Should be styled as shown in [specks](https://drive.google.com/drive/u/0/folders/0B1LbmKnex41fMkVfWFhSUlR3eGM)

**Comment by amolskh** [comment]
I am doing this 

Regards

**Comment by vikasrohit** [comment]
Go ahead :+1:

**Comment by amolskh** [comment]
I have submitted the pull request

**Comment by vikasrohit** [comment]
@amolskh 
Final fixes:
- [ ] Can we reuse TaggedValue and/or TaggedValueList components for these two components?

**Comment by amolskh** [comment]
Yes we can use ..Do you mean currently PrizeList component should referred internally to taggedList component

Please confirm..

**Comment by vikasrohit** [comment]
Didn't get your point @amolskh. We would still have PrizeItem and PrizeItemList components, however, they would delegate actual rendering to TaggedValue and TaggedValueList components respectively. We can either inherit TaggedValue in PrizeItem and TaggedValueList in PrizeItemList or just encapsulate TaggedValue in PrizeItem and TaggedValueList in PrizeList. It would be more clear, which one to use, when you try to implement one of them ways. Personally, I would prefer the inheritance way.

**Comment by vikasrohit** [comment]
@amolskh Do you need further clarification for final fix?

**Comment by amolskh** [comment]
Sorry for the delay.. I have made PR please review and merge
