### ISSUE TITLE
SubtrackDetails React component

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/react-components#54]
**Requirements**
- [x] Should follow the style described in [specks](https://drive.google.com/drive/u/0/folders/0B1LbmKnex41fMkVfWFhSUlR3eGM)
- [x] Track code (colored bars in top left of the component)  - represents for which main track the tooltip applies (can be combo of all 3 i.e. develop, design, data science)
- [x] Tracks, subtrack name, subtrack code and subtrack description should be configurable via properties.
- [x] Subtrack description should be shown only if available i.e. it should not block the space when description is not provided.

**Comment by amolskh** [comment]
I am doing this 

Regards

**Comment by vikasrohit** [comment]
May I know your topcoder handle?

**Comment by amolskh** [comment]
code56Life

**Comment by vikasrohit** [comment]
:+1: Go ahead.

**Comment by amolskh** [comment]
Pull request has been submitted Please review and let me know if any changes required

**Comment by vikasrohit** [comment]
Marking issue in final fix.

**Comment by vikasrohit** [comment]
@amolskh you can do the final fixes after submission phase.

Final Fixes:

- [ ] Can we have one example for the component where only one track applies and another with two tracks being applied?
- [ ] Can we have example where description is not set?

**Comment by amolskh** [comment]
PR done .. Please review final fixes

**Comment by vikasrohit** [comment]
Thanks @amolskh I have merged the branch. Please check if it creates conflicts for your other PRs. We will keep the issue open until challenge end so that we don't forget to pay for it. :grin:
