### ISSUE TITLE
MenuNav should use Link component and not anchor tag directly

### ISSUE THREAD

**Issue by parthshah** [appirio-tech/react-components#86]
See https://github.com/reactjs/react-router/blob/master/docs/API.md#link for more information

**Comment by vikasrohit** [comment]
@parthshah it would bind components with redux and we would not be able to render it in legacy or even angular apps without referencing redux.

**Comment by parthshah** [comment]
Did you mean react-router dependency? AFAIK this has no dependency on redux.

**Comment by vikasrohit** [comment]
yup, sorry... I was concerned about react-router.

**Comment by parthshah** [comment]
We already have a dependency on React-router. But in case we have a problem
with legacy apps, maybe we can create a new component LinkMenuNav ?

**Comment by vikasrohit** [comment]
Agreed. Even I have added a property(forReactRouter) in the MenuBar react component to use React Router's Link component of not.
