### ISSUE TITLE
Nav Bar || Quick Links Dropdown menu

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/react-components#9]
This component contains quick links for easy access to different applications under the Topcoder platform.

Component tree

- quick-links-dropdown-menu
  - dropdown-menu-header
    - img(.quick-links-icon)
  - dropdown-menu-list(.quick-links-list)
    - std-list-item(.quick-link-item)

Requirements:
- Create a branch off of master and make a PR to master
- Should be responsive to support the mobile layout as rendered in the design specks
- Reuse the dropdown-menu component

**Comment by reynard2007** [comment]
Taking this. Creating  branch off of dev instead as mentioned in the challenge description

**Comment by vikasrohit** [comment]
Closing task. Thanks @reynard2007 for your hard work.
